version: "3"
services: 
  flask:
    build: .
    ports: 
      - "5000:5000"
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "WeShare"
      MYSQL_ROOT_PASSWORD: "glo2005"
    ports:
      - "3306:3306"
    volumes:
      - ./bd_init:/docker-entrypoint-initdb.d/:ro

  vuejs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
     - flask
    links:
     - flask
    